// AUTOGENERATED: Test Fixtures - Production Ready - 2025-01-05
import { test as base, type Page } from '@playwright/test';
import { AccountPage } from '../page-objects/AccountPage.js';
import { TEST_CONFIG, USER_DATA } from '../data/test-data.js';

type TestFixtures = {
  accountPage: AccountPage;
  authenticatedPage: Page;
};

export const test = base.extend<TestFixtures>({
  // Account page fixture with smart initialization
  accountPage: async ({ page }: { page: Page }, use: (accountPage: AccountPage) => Promise<void>) => {
    const accountPage = new AccountPage(page);
    await use(accountPage);
  },

  // Pre-authenticated page fixture for tests requiring login
  authenticatedPage: async ({ page }: { page: Page }, use: (page: Page) => Promise<void>) => {
    const accountPage = new AccountPage(page);
    
    try {
      await page.goto(TEST_CONFIG.baseUrl);
      await accountPage.navigateToLogin();
      await accountPage.login(USER_DATA.valid.email, USER_DATA.valid.password);
      
      const isAuth = await accountPage.isAuthenticated();
      if (!isAuth) {
        throw new Error('Authentication failed in fixture');
      }
      
      console.log('✅ Authenticated fixture ready');
    } catch (error) {
      console.log(`❌ Authentication fixture failed: ${error}`);
      // Continue with unauthenticated page for graceful degradation
    }
    
    await use(page);
  }
});

export { expect } from '@playwright/test';