// AUTOGENERATED: Centralized Test Data - Production Ready - 2025-01-05

export const TEST_CONFIG = {
  baseUrl: process.env.BASE_URL || 'https://www.mitre10.co.nz',
  timeout: {
    default: 30000,
    navigation: 15000,
    element: 10000,
    api: 5000
  },
  performance: {
    pageLoad: 5000,
    apiResponse: 3000,
    elementInteraction: 1000
  }
};

export const USER_DATA = {
  valid: {
    email: process.env.TEST_USER_EMAIL || 'test@example.com',
    password: process.env.TEST_USER_PASSWORD || 'CHANGE_ME_SECURE_PASSWORD'
  },
  invalid: {
    email: 'invalid@test.com',
    // amazonq-ignore-next-line
    password: 'wrongpassword'
  }
};

export const SEARCH_DATA = {
  products: ['drill', 'hammer', 'screwdriver', 'paint'],
  categories: ['tools', 'hardware', 'garden', 'lighting'],
  noResults: 'xyznonexistentproduct123456789'
};

export const MOBILE_CONFIG = {
  devices: {
    iphone: { width: 393, height: 852 },
    android: { width: 412, height: 915 },
    tablet: { width: 768, height: 1024 }
  },
  touchTargetSize: 44 // iOS HIG minimum
};

export const ACCOUNT_SECTIONS = [
  'My details',
  'My addresses', 
  'My orders',
  'Wishlist',
  'Club',
  'Airpoints',
  'Communication'
];

export const EXPECTED_ELEMENTS = {
  homepage: ['search', 'navigation', 'header', 'footer'],
  account: ['dashboard', 'profile', 'orders', 'addresses'],
  search: ['results', 'filters', 'products', 'pagination'],
  product: ['title', 'price', 'description', 'add-to-cart']
};