// AUTOGENERATED: Adaptive Mitre 10 navigation test suite - 2025-01-28
import { test, expect } from '@playwright/test';
import { BrowserUtils } from '../../utils/browser-utils.js';

test.describe('🌐 Mitre 10 Adaptive Navigation & Content Validation', () => {
  
  test.beforeEach(async ({ page }) => {
    await BrowserUtils.handlePopups(page);
  });

  test('🏠 Homepage navigation exploration', async ({ page }) => {
    await test.step('🌐 Navigate to Mitre 10 homepage', async () => {
      await page.goto('https://www.mitre10.co.nz/');
      await BrowserUtils.waitForStableLoad(page, 6000);
      await expect(page).toHaveTitle(/Mitre 10/);
    });

    await test.step('🔍 Explore available navigation options', async () => {
      const isMobile = await BrowserUtils.isMobile(page);
      
      // Check for various navigation patterns
      const navOptions = [
        'Departments',
        'Services', 
        'Club',
        'Inspiration',
        'Easy As',
        'Guides',
        'Trade'
      ];
      
      let foundNavItems = 0;
      for (const option of navOptions) {
        const navLink = page.getByRole('link', { name: new RegExp(option, 'i') }).first();
        if (await navLink.isVisible({ timeout: 2000 }).catch(() => false)) {
          console.log(`✅ Found navigation: ${option}`);
          foundNavItems++;
        }
      }
      
      expect(foundNavItems).toBeGreaterThan(0);
      console.log(`✅ Found ${foundNavItems} navigation items`);
    });
  });

  test('🎨 Dreamzone/Inspiration page validation', async ({ page }) => {
    await test.step('🌐 Navigate to Inspiration/Dreamzone', async () => {
      await page.goto('https://www.mitre10.co.nz/');
      await BrowserUtils.waitForStableLoad(page, 6000);
      
      // Try multiple inspiration-related links
      const inspirationSelectors = [
        page.getByRole('link', { name: /inspiration/i }),
        page.getByRole('link', { name: /dreamzone/i }),
        page.getByRole('link', { name: /ideas/i })
      ];
      
      let navigated = false;
      for (const selector of inspirationSelectors) {
        if (await selector.first().isVisible({ timeout: 2000 }).catch(() => false)) {
          await selector.first().click();
          navigated = true;
          break;
        }
      }
      
      if (!navigated) {
        // Direct navigation if link not found
        await page.goto('https://www.mitre10.co.nz/dreamzone');
      }
    });

    await test.step('🖼️ Verify content and media', async () => {
      // Wait for any URL that indicates inspiration/dreamzone content
      await page.waitForLoadState('networkidle');
      
      // Check images are loaded
      const images = page.locator('img');
      const imageCount = await images.count();
      
      if (imageCount > 0) {
        let loadedImages = 0;
        for (let i = 0; i < Math.min(5, imageCount); i++) {
          const img = images.nth(i);
          const naturalWidth = await img.evaluate((el: HTMLImageElement) => el.naturalWidth).catch(() => 0);
          if (naturalWidth > 0) {
            loadedImages++;
          }
        }
        console.log(`✅ ${loadedImages}/${Math.min(5, imageCount)} images loaded`);
      }
      
      // Check for any content structure
      const contentElements = page.locator('main, .content, .page-content, article').first();
      await expect(contentElements).toBeVisible({ timeout: 5000 });
      console.log('✅ Inspiration/Dreamzone content validated');
    });
  });

  test('🏆 Club page navigation and functionality', async ({ page }) => {
    await test.step('🌐 Navigate to Club page', async () => {
      await page.goto('https://www.mitre10.co.nz/');
      await BrowserUtils.waitForStableLoad(page, 6000);
      
      const clubLink = page.getByRole('link', { name: /club/i }).first();
      if (await clubLink.isVisible({ timeout: 3000 }).catch(() => false)) {
        await clubLink.click();
      } else {
        // Direct navigation if link not found
        await page.goto('https://www.mitre10.co.nz/club');
      }
    });

    await test.step('📋 Verify Club page and interactive elements', async () => {
      await page.waitForLoadState('networkidle');
      
      // Look for any tab-like elements
      const tabSelectors = [
        '[role="tab"]',
        '.tab',
        '.nav-tab',
        '[class*="tab"]',
        'button[aria-selected]',
        '.active'
      ];
      
      let tabsFound = 0;
      for (const selector of tabSelectors) {
        const tabs = page.locator(selector);
        const count = await tabs.count();
        if (count > 0) {
          tabsFound += count;
          console.log(`✅ Found ${count} elements matching ${selector}`);
          
          // Try clicking first few tabs
          for (let i = 0; i < Math.min(3, count); i++) {
            const tab = tabs.nth(i);
            if (await tab.isVisible({ timeout: 1000 }).catch(() => false)) {
              await tab.click();
              await page.waitForTimeout(500);
            }
          }
        }
      }
      
      console.log(`✅ Club page validated with ${tabsFound} interactive elements`);
    });
  });

  test('🔧 Services page validation', async ({ page }) => {
    await test.step('🌐 Navigate to Services page', async () => {
      await page.goto('https://www.mitre10.co.nz/');
      await BrowserUtils.waitForStableLoad(page, 6000);
      
      const servicesLink = page.getByRole('link', { name: /services/i }).first();
      if (await servicesLink.isVisible({ timeout: 3000 }).catch(() => false)) {
        await servicesLink.click();
      } else {
        await page.goto('https://www.mitre10.co.nz/services');
      }
    });

    await test.step('🔗 Validate Services content', async () => {
      await page.waitForLoadState('networkidle');
      
      // Check for service-related links and content
      const serviceElements = page.locator('a[href*="service"], a[href*="hire"], .service, [class*="service"]');
      const elementCount = await serviceElements.count();
      
      console.log(`✅ Found ${elementCount} service-related elements`);
      
      // Verify page has content
      const mainContent = page.locator('main, .content, .page-content, body').first();
      await expect(mainContent).toBeVisible();
      console.log('✅ Services page content validated');
    });
  });

  test('🏢 Trade page comprehensive validation', async ({ page }) => {
    await test.step('🌐 Navigate to Trade page', async () => {
      await page.goto('https://www.mitre10.co.nz/trade');
      await BrowserUtils.waitForStableLoad(page, 8000);
    });

    await test.step('🔗 Validate Trade page structure and links', async () => {
      await expect(page).toHaveURL(/.*trade.*/);
      
      // Check for trade-specific content
      const tradeElements = page.locator('a[href*="trade"], a[href*="business"], [class*="trade"]');
      const elementCount = await tradeElements.count();
      
      console.log(`✅ Found ${elementCount} trade-related elements`);
      
      // Test some trade links
      if (elementCount > 0) {
        for (let i = 0; i < Math.min(3, elementCount); i++) {
          const element = tradeElements.nth(i);
          const href = await element.getAttribute('href');
          if (href && href !== '#') {
            console.log(`✅ Trade link: ${href}`);
          }
        }
      }
      
      // Verify page has meaningful content
      const pageContent = page.locator('main, .content, .page-content, body').first();
      await expect(pageContent).toBeVisible();
      console.log('✅ Trade page validated');
    });
  });

  test('📚 Guides and content exploration', async ({ page }) => {
    await test.step('🌐 Explore guides and content pages', async () => {
      await page.goto('https://www.mitre10.co.nz/');
      await BrowserUtils.waitForStableLoad(page, 6000);
      
      // Look for guides, help, or content links
      const contentLinks = [
        page.getByRole('link', { name: /guides/i }),
        page.getByRole('link', { name: /easy as/i }),
        page.getByRole('link', { name: /help/i }),
        page.getByRole('link', { name: /how to/i })
      ];
      
      let foundContent = false;
      for (const link of contentLinks) {
        if (await link.first().isVisible({ timeout: 2000 }).catch(() => false)) {
          await link.first().click();
          foundContent = true;
          console.log(`✅ Navigated to content via: ${await link.first().textContent()}`);
          break;
        }
      }
      
      if (!foundContent) {
        console.log('ℹ️ No specific guides link found, checking current page content');
      }
    });

    await test.step('🎥 Check for multimedia content', async () => {
      await page.waitForLoadState('networkidle');
      
      // Look for YouTube videos or other media
      const mediaSelectors = [
        'iframe[src*="youtube"]',
        'iframe[src*="youtu.be"]',
        'iframe[src*="vimeo"]',
        'video',
        '[class*="video"]'
      ];
      
      let mediaFound = 0;
      for (const selector of mediaSelectors) {
        const media = page.locator(selector);
        const count = await media.count();
        if (count > 0) {
          mediaFound += count;
          console.log(`✅ Found ${count} ${selector} elements`);
          
          // Test interaction with first media element
          const firstMedia = media.first();
          if (await firstMedia.isVisible({ timeout: 2000 }).catch(() => false)) {
            await firstMedia.click();
            await page.waitForTimeout(1000);
            console.log('✅ Media interaction tested');
          }
        }
      }
      
      console.log(`✅ Total media elements found: ${mediaFound}`);
    });
  });

  test('🔗 Comprehensive link validation', async ({ page }) => {
    const testUrls = [
      'https://www.mitre10.co.nz/',
      'https://www.mitre10.co.nz/trade'
    ];

    for (const url of testUrls) {
      await test.step(`🔍 Testing links on ${url}`, async () => {
        await page.goto(url);
        await BrowserUtils.waitForStableLoad(page, 6000);
        
        // Get all valid links
        const allLinks = page.locator('a[href]:not([href="#"]):not([href^="javascript:"])');
        const linkCount = await allLinks.count();
        
        if (linkCount > 0) {
          console.log(`✅ Found ${linkCount} valid links on ${url}`);
          
          // Test random selection of links
          const linksToTest = Math.min(5, linkCount);
          const testedLinks = new Set();
          
          for (let i = 0; i < linksToTest; i++) {
            let randomIndex;
            do {
              randomIndex = Math.floor(Math.random() * linkCount);
            } while (testedLinks.has(randomIndex));
            
            testedLinks.add(randomIndex);
            const link = allLinks.nth(randomIndex);
            
            const href = await link.getAttribute('href');
            const target = await link.getAttribute('target');
            
            if (href) {
              const isExternal = href.startsWith('http') && !href.includes('mitre10.co.nz');
              const opensNewTab = target === '_blank' || isExternal;
              
              console.log(`✅ ${opensNewTab ? 'External' : 'Internal'} link: ${href}`);
            }
          }
        }
      });
    }
  });

  test('🖼️ Media and accessibility validation', async ({ page }) => {
    await test.step('🌐 Load homepage for comprehensive media check', async () => {
      await page.goto('https://www.mitre10.co.nz/');
      await BrowserUtils.waitForStableLoad(page, 8000);
    });

    await test.step('🖼️ Validate images and media loading', async () => {
      const images = page.locator('img');
      const imageCount = await images.count();
      let loadedImages = 0;
      let imagesWithAlt = 0;
      
      // Check first 10 images for loading and accessibility
      for (let i = 0; i < Math.min(10, imageCount); i++) {
        const img = images.nth(i);
        
        // Check if image loaded
        const naturalWidth = await img.evaluate((el: HTMLImageElement) => el.naturalWidth).catch(() => 0);
        if (naturalWidth > 0) {
          loadedImages++;
        }
        
        // Check for alt text
        const alt = await img.getAttribute('alt');
        if (alt !== null) {
          imagesWithAlt++;
        }
      }
      
      console.log(`✅ Images: ${loadedImages}/${Math.min(10, imageCount)} loaded, ${imagesWithAlt} with alt text`);
      expect(loadedImages).toBeGreaterThan(0);
    });

    await test.step('🧭 Validate navigation accessibility', async () => {
      const isMobile = await BrowserUtils.isMobile(page);
      
      // Check navigation structure
      const navElements = page.locator('nav, [role="navigation"], .navigation, .nav');
      const navCount = await navElements.count();
      
      if (navCount > 0) {
        console.log(`✅ Found ${navCount} navigation elements`);
        
        // Check for keyboard accessibility
        const focusableElements = page.locator('a, button, input, select, textarea, [tabindex]:not([tabindex="-1"])');
        const focusableCount = await focusableElements.count();
        console.log(`✅ Found ${focusableCount} focusable elements`);
      }
      
      // Check footer
      const footer = page.locator('footer, .footer, [role="contentinfo"]');
      const footerCount = await footer.count();
      if (footerCount > 0) {
        const footerLinks = footer.locator('a[href]');
        const footerLinkCount = await footerLinks.count();
        console.log(`✅ Footer contains ${footerLinkCount} links`);
      }
      
      console.log('✅ Navigation and accessibility validation completed');
    });
  });
});